### ISSUE TITLE
Add comments to Gruntfile.js and README.md

### ISSUE THREAD

**Issue by hhzl** [amber-smalltalk/trysmalltalk#1]
For version 0.13 the ``Gruntfile.js`` had to be customized manually. Add some comments in the README.md file and in the ``Gruntfile.js`` how this had been done.

See https://github.com/amber-smalltalk/amber/issues/1012#issuecomment-68696521

**Comment by tomrake** [comment]
I derived the entire repo from amber-examples repo. If you look at https://github.com/amber-smalltalk/trysmalltalk/blame/master/Gruntfile.js you see that @hhzl  make the last changes on November 5.

I changed bower.json to use amber.0.13.3 and advanced the patch level to 0.1.1

I changed the reflection lesson to use #install:forClass:protocol: in TrySmalltalk.st

**Comment by hhzl** [comment]
@tomrake thank you for your comments. The note about adding comments was meant for me as I trimmed down the  ``Gruntfile.js`` generated by ``amber init``.
