### ISSUE TITLE
Do a bower entry

### ISSUE THREAD

**Issue by hhzl** [amber-smalltalk/trysmalltalk#11]
http://bower.io/search/?q=trysmalltalk

does not yet give a result.

**Comment by hhzl** [comment]
Is ``bower.json`` correct?

Then see
http://bower.io/docs/creating-packages/

**Comment by tomrake** [comment]
It is marked private in the bower.json. For a public release we need to decide on a version as well.

**Comment by hhzl** [comment]
I suggest to wait until version 0.14.1 of this repo has been released and #5 is closed.

**Comment by hhzl** [comment]
private attribute in ``bower.json`` has been removed. ``trysmalltalk`` now shows up at ``bower.io``
![bower-search-for-trysmalltalk_2015-01-24](https://cloud.githubusercontent.com/assets/1112023/5886505/b2bf16ee-a39a-11e4-9236-ef02e2723d74.png)


What is needed next is a text how to use it as a library. The bower.io page link sends the user directly to the README.md which is geared at developers of ``trysmalltalk``.

**Comment by herby** [comment]
Isn't this already solved and should be closed?

**Comment by hhzl** [comment]
Yes, we now have a bower entry for trysmalltalk. In this sense it is solved.

My comment was about the instructions somebody should follow and wants to **include** trysmalltalk into his or her web site. Not about what they should to contribute to the development of trysmalltalk.

Cf. other bower entries.

**Comment by herby** [comment]
But isn't it another issue? Maybe I am unnecessarily strict, but I like if issue is about what the title says. It's clearer than what is done and what is open, especially for newcomers not involved in thread conversations.

Hannes Hirzel wrote:

**Comment by hhzl** [comment]
I agree, it is another issue.
