### ISSUE TITLE
0.14.2 deployment mode -- "ProfStef next" is not executed

### ISSUE THREAD

**Issue by hhzl** [amber-smalltalk/trysmalltalk#15]
In deployment mode (``grunt deploy``, use of ``index.html`` and ``the.js`` only) selecting a code snippet, e.g. ``ProfStef next`` and clicking the ``DoIt`` button does not work.

See https://github.com/hhzl/trysmalltalk0142/issues/1

**Comment by herby** [comment]
Of course, the whole compiler suite is missing, as amber deploy packs in amber/deploy which lacks compiler.

If you need compiler in deployment (which is this case; often you don't need it that's why amber/deploy is so minimal), change 'amber/deploy' to 'amber/lang' (=deploy+compiler) in deploy.js.

Hannes Hirzel wrote:

**Comment by hhzl** [comment]
**Confirmation**

``deploy.js`` should be different for the case where you want to deploy with ``index.html`` and ``the.js`` only.

Instead of
````
define([
    'amber/deploy',
    // --- packages to be deployed begin here ---
    'amber-attic/IDE',
    'amber-trysmalltalk/TrySmalltalk'
    // --- packages to be deployed end here ---
], function (amber) {
    return amber;
}); 
````

have a ``deploy.js``  with **amber/lang**

````
define([
    'amber/lang',
    // --- packages to be deployed begin here ---
    'amber-attic/IDE',
    'amber-trysmalltalk/TrySmalltalk'
    // --- packages to be deployed end here ---
], function (amber) {
    return amber;
});
````

**Comment by herby** [comment]
What do you mean by deploy.js should be different for the case where you want to deploy with index.html and the.js only"? The file deploy.js is exactly for that case, why do you pointing it out. Also, it sounds as if it was general advice for any other project, which it isn't.

Hannes Hirzel wrote:
> *Confirmation*
>
> |deploy.js| should be different for the case where you want to deploy 
> with |index.html| and |the.js| only.
>
> Instead of
>
> |define([
>      'amber/deploy',
>      // --- packages to be deployed begin here ---
>      'amber-attic/IDE',
>      'amber-trysmalltalk/TrySmalltalk'
>      // --- packages to be deployed end here ---
> ], function (amber) {
>      return amber;
> });
> |
>
> have a |deploy.js| with *amber/lang*
>
> |define([
>      'amber/lang',
>      // --- packages to be deployed begin here ---
>      'amber-attic/IDE',
>      'amber-trysmalltalk/TrySmalltalk'
>      // --- packages to be deployed end here ---
> ], function (amber) {
>      ret
urn amber;

**Comment by hhzl** [comment]
I agree. I shortened the previous comment. 

Working with ``deploy.js`` means that ``index.html`` and ``the.js`` are going to be used. 

For TrySmalltalk the compiler is needed, ergo ``amber/lang`` in deploy.js.
