### ISSUE TITLE
Tag/relasee trysmalltalk at 0.1.3

### ISSUE THREAD

**Issue by tomrake** [amber-smalltalk/trysmalltalk#19]
I had previously used 0.1.1 and 0.1.2 and had not pushed the tags when the amber-smalltalk repo was created. We should tag for easier bower reference.

**Comment by herby** [comment]
You can tag 0.1.1 and 0.1.2 now as well, no need to wait for 0.1.3. Just make the tags and push them.

Tom Rake wrote:
