### ISSUE TITLE
Add node_modules to .gitignore file in gh-pages branch

### ISSUE THREAD

**Issue by hhzl** [amber-smalltalk/trysmalltalk#21]
as just done on https://github.com/amber-smalltalk/amber-website/commit/bc812f63a60777ac7a813494841d3f9ed33ae1e5

**Comment by tomrake** [comment]
This is really amber-website issue and take care of by https://github.com/amber-smalltalk/amber-website/issues/24

**Comment by hhzl** [comment]
I think this is a misunderstandig, why should the ``node_modules`` folder be in https://github.com/amber-smalltalk/trysmalltalk/tree/gh-pages?

**Comment by herby** [comment]
@hhzl What words from "to .gitignore file" did you not understand? ;-)

**Comment by herby** [comment]
Or maybe I did not understand and it's a bit more complicated :-\ Never mind, I hope you resolve it somehow.

**Comment by hhzl** [comment]
What I mean that a line

     node_modules/

should be in the file

https://github.com/amber-smalltalk/trysmalltalk/blob/gh-pages/.gitignore

Correct?

**Comment by herby** [comment]
Oh yes, sorry. I was mistakenly looking at the one in master and it was ok, so I was puzzled why was this reopened and all.

**Comment by herby** [comment]
They are needed to actually be deleted, though, they are still there (`node_modules` in gh-pages).

**Comment by hhzl** [comment]
Done, see 
https://github.com/amber-smalltalk/trysmalltalk/issues/22
https://github.com/amber-smalltalk/trysmalltalk/issues/26
