### ISSUE TITLE
Deploy without bower_components

### ISSUE THREAD

**Issue by herby** [amber-smalltalk/trysmalltalk#22]
First, you will see if the.js and learn.html are enough so deploying works, second, the ide-starter overlay stops to appear.

Probably do this after #4.

**Comment by hhzl** [comment]
+1

**Comment by tomrake** [comment]
I am going to try this I just added a PR to close #4 and see if this works.

**Comment by hhzl** [comment]
Current ``deploy.js`` is

````
define([
    'amber/deploy',
    // --- packages to be deployed begin here ---
    'amber-attic/IDE',
    'amber-trysmalltalk/TrySmalltalk'
    // --- packages to be deployed end here ---
], function (amber) {
    return amber;
});
````

`` 'amber-attic/IDE',`` should be moved to ``devel.js``

**Comment by herby** [comment]
No, it shouldn't. ProfStef examples rely on IDE presence, that's why it is in deploy.js, by design.

Dňa 27. júna 2015 17:40:36 CEST používateľ Hannes Hirzel <notifications@github.com> napísal:

**Comment by hhzl** [comment]
OK, ``'amber-attic/IDE'`` it has to remain in ``deploy.js``.

````index.html```` and ````the.js```` work fine if left in the environment where ````bower_components```` are. 

As soon as copied to a ````dist```` directory it stops working giving a very unspecific error message.

![trysmalltalk_2015-06-27 16 20 26](https://cloud.githubusercontent.com/assets/1112023/8392874/d8ff7aac-1ce8-11e5-91d0-b1e6782448d0.png)

**Comment by hhzl** [comment]
The result after `` bower install "amber-attic#^0.1.5" ``

![trysmalltalk_b_2015-06-27 16 34 46](https://cloud.githubusercontent.com/assets/1112023/8392965/bf9d1b8a-1cea-11e5-9156-023b9b0182e5.png)

**Comment by herby** [comment]
In fact, it has moved to amber-contrib-legacy, as outlined in on of the migration guide, so it would be good to migrate this project as well.

Dňa 27. júna 2015 18:24:50 CEST používateľ Hannes Hirzel <notifications@github.com> napísal:

**Comment by hhzl** [comment]
Following and adapting [Migration-from-0.14.12-to-0.14.13](https://github.com/amber-smalltalk/amber/wiki/Migration-from-0.14.12-to-0.14.13) it would need

````
bower install "amber#^0.14.13" --save
bower install "helios#^0.4.3" --save-dev
bower uninstall amber-attic 
bower install "amber-contrib-legacy#^0.2.0" 
grunt devel
````

Is this correct?

**Comment by hhzl** [comment]
after doing the above
````
grunt deploy
Running "amdconfig:app" (amdconfig) task

Running "requirejs:deploy" (requirejs) task
Error: ENOENT, no such file or directory '/media/user/Amber/amber-dev/trysmalltalk/amber-contrib-legacy/IDE.js'
In module tree:
    deploy

{ [Error: Error: ENOENT, no such file or directory '/media/user/Amber/amber-dev/trysmalltalk/amber-contrib-legacy/IDE.js'
In module tree:
    deploy

    at Object.fs.openSync (fs.js:432:18)
]
  originalError: 
   { [Error: ENOENT, no such file or directory '/media/user/Amber/amber-dev/trysmalltalk/amber-contrib-legacy/IDE.js']
     errno: 34,
     code: 'ENOENT',
     path: '/media/user/Amber/amber-dev/trysmalltalk/amber-contrib-legacy/IDE.js',
     syscall: 'open',
     fileName: '/media/user/Amber/amber-dev/trysmalltalk/amber-contrib-legacy/IDE.js',
     moduleTree: [ 'deploy' ] } }
````

IDE.js 
is in
/media/user/Amber/amber-dev/trysmalltalk/bower_components/amber-contrib-legacy/src

So a mapping is needed?

**Comment by hhzl** [comment]
Mapping: ``deploy.js``

````
define([
    'amber/lang',
    // --- packages to be deployed begin here ---
    'amber/legacy/IDE',
    'amber-trysmalltalk/TrySmalltalk'
    // --- packages to be deployed end here ---
], function (amber) {
    return amber;
});
````


``'amber/legacy/IDE'`` contains the compiler and needs to be deployed.


``bower.json`` is now

````
{
  "name": "trysmalltalk",
  "description": "Tutorial to learn Smalltalk",
  "version": "0.1.1",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "/test_runner.js",
    "test",
    "tests",
    "/config.js",
    "/the.js"
  ],
  "authors": [
    {
      "name": "hhzl",
      "email": "hannes.hirzel@gmail.com"
    }
  ],
  "homepage": "https://github.com/amber-smalltalk/trysmalltalk",
  "keywords": [
    "Amber",
    "Smalltalk"
  ],
  "license": [
    "MIT"
  ],
  "dependencies": {
    "amber": "^0.14.13"
  },
  "devDependencies": {
    "amber-ide-starter-dialog": "^0.1.0",
    "helios": "^0.4.3"
  },
  "resolutions": {
    "amber": "^0.14.13",
    "helios": "^0.4.3"
  }
}

**Comment by hhzl** [comment]
Is fixed with https://github.com/amber-smalltalk/trysmalltalk/pull/29

**Comment by herby** [comment]
Dňa 28. júna 2015 17:27:07 CEST používateľ Hannes Hirzel <notifications@github.com> napísal:
> Mapping: ``deploy.js``
> 
> ````
> define([
>     'amber/lang',
>     // --- packages to be deployed begin here ---
>     'amber/legacy/IDE',
>     'amber-trysmalltalk/TrySmalltalk'
>     // --- packages to be deployed end here ---
> ], function (amber) {
>     return amber;
> });
> ````
> 
> 
> ``'amber/legacy/IDE'`` contains the compiler and needs to be deployed.

No, amber/lang contains compiler. IDE is there for IDE functionalities like Inspector or Browser some of which are required by certain lessons.


> 
> 
> ``bower.json`` is now
> 
> ````
> {
>   "name": "trysmalltalk",
>   "description": "Tutorial to learn Smalltalk",
>   "version": "0.1.1",
>   "ignore": [
>     "**/.*",
>     "node_modules",
>     "bower_components",
>     "/test_runner.js",
>     "test",
>     "tests",
>     "/config.js",
>     "/the.js"
>   ],
>   "authors": [
>     {
>       "name": "hhzl",
>       "email": "hannes.hirzel@gmail.com"
>     }
>   ],
>   "homepage": "https://github.com/amber-smalltalk/trysmalltalk",
>   "keywords": [
>     "Amber",
>     "Smalltalk"
>   ],
>   "license": [
>     "MIT"
>   ],
>   "dependencies": {
>     "amber": "^0.14.13"

Where is dependency for the IDE?

>   },
>   "devDependencies": {
>     "amber-ide-starter-dialog": "^0.1.0",
>     "helios": "^0.4.3"
>   },
>   "resolutions": {

This section should not be present. If there are problems, they should be solved other ways.

**Comment by herby** [comment]
Hannes Hirzel wrote:
> Following and adapting Migration-from-0.14.12-to-0.14.13
> <https://github.com/amber-smalltalk/amber/wiki/Migration-from-0.14.12-to-0.14.13>
> it would need
>
> |bower install "amber#^0.14.13" --save
> bower install "helios#^0.4.3" --save-dev

There is newer helios, already. "helios#*" is more generic (but then you 
need to edit bower.json to switch '~' to '^'.

> bower uninstall amber-attic
> bower install "amber-contrib-legacy#^0.2.0"

In these two lines there should normally be --save-dev but here it 
should be --save.

**Comment by hhzl** [comment]
When I do 

    bower install "amber-contrib-legacy#^0.2.0" --save


I get 
![trysmalltalk_amber_version_resolution_2015-06-29](https://cloud.githubusercontent.com/assets/1112023/8405315/1f46a624-1e43-11e5-8e28-3eec56e79554.png)

and this results in a ``"resolutions": {...}`` section in ``bower.json``.

@herby what are the other means you are referring to for solving this?

**Comment by herby** [comment]
Isn't the solution obvious? Helios 0.4.4 is blocked on certain amber version, so get the currenr helios instead of the old one?

Dňa 29. júna 2015 11:43:38 CEST používateľ Hannes Hirzel <notifications@github.com> napísal:

**Comment by hhzl** [comment]
OK, I now do

``bower install "helios#" --save-dev``

and the questions for resolutions are

![trysmallatalk_b_2015-06-29](https://cloud.githubusercontent.com/assets/1112023/8407468/41a8642e-1e56-11e5-953b-4f3198457ab3.png)


And ``bower.json`` is

````
{
  "name": "trysmalltalk",
  "description": "Tutorial to learn Smalltalk",
  "version": "0.1.1",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "/test_runner.js",
    "test",
    "tests",
    "/config.js",
    "/the.js"
  ],
  "authors": [
    {
      "name": "hhzl",
      "email": "hannes.hirzel@gmail.com"
    }
  ],
  "homepage": "https://github.com/amber-smalltalk/trysmalltalk",
  "keywords": [
    "Amber",
    "Smalltalk"
  ],
  "license": [
    "MIT"
  ],
  "dependencies": {
    "amber": "^0.14.13",
    "amber-contrib-legacy": "^0.2.0"
  },
  "devDependencies": {
    "amber-ide-starter-dialog": "^0.1.0",
    "helios": "~0.5.2"
  },
  "resolutions": {
    "amber": "^0.14.13",
    "helios": "~0.5.2",
    "showdown": "^0.5.0"
  }
}
````
@herby you say that now the following section is unnecessary?

````
"resolutions": {
    "amber": "^0.14.13",
    "helios": "~0.5.2",
    "showdown": "^0.5.0"
  }
````

**Comment by hhzl** [comment]
``bower install`` answers the question

````
 bower install
bower helios          extra-resolution Unnecessary resolution: helios#~0.5.2
bower showdown        extra-resolution Unnecessary resolution: showdown#^0.5.0
````

So ``bower.json`` is now

````
{
  "name": "trysmalltalk",
  "description": "Tutorial to learn Smalltalk",
  "version": "0.1.1",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "/test_runner.js",
    "test",
    "tests",
    "/config.js",
    "/the.js"
  ],
  "authors": [
    {
      "name": "hhzl",
      "email": "hannes.hirzel@gmail.com"
    }
  ],
  "homepage": "https://github.com/amber-smalltalk/trysmalltalk",
  "keywords": [
    "Amber",
    "Smalltalk"
  ],
  "license": [
    "MIT"
  ],
  "dependencies": {
    "amber": "^0.14.13",
    "amber-contrib-legacy": "^0.2.0"
  },
  "devDependencies": {
    "amber-ide-starter-dialog": "^0.1.0",
    "helios": "^0.5.2"
  }
}
````

**Comment by hhzl** [comment]
``index.html`` and ``the.js`` are now sufficient for deployment after ``grunt deploy``.

It is now left with updating the ``gh-pages`` branch and removing ``bower_components`` and ``nodemodules`` there by adding them to ``.gitignore``.

**Comment by hhzl** [comment]
https://github.com/amber-smalltalk/trysmalltalk/tree/gh-pages updated

http://amber-smalltalk.github.io/trysmalltalk/

has now

``Smalltalk version  '0.14.16' ``
