### ISSUE TITLE
error in example in step 21/24 

### ISSUE THREAD

**Issue by michalbcz** [amber-smalltalk/trysmalltalk#30]
http://amber-lang.net/learn.html in step **21/24** there is:

```
Array new
	add: 'Some text';
	add: 3.;
	yourself.
```

but it's evaluation ends with an error. There is erroneous  **.** (dot) after 3 in third row. It should be:

```
Array new
	add: 'Some text';
	add: 3;
	yourself.

```

**Comment by michalbcz** [comment]
It was already fixed in the code (commit: https://github.com/amber-smalltalk/trysmalltalk/commit/9f178258fd1ecfd6face39847c7db03049132dad), but it is not deployed yet :(

**Comment by herby** [comment]
Let me try to... maybe it'll work (not only I need to publish new version here, but also make https://github.com/amber-smalltalk/amber-website updated and deployed).

**Comment by herby** [comment]
Done (took some time as updating all things was a bit long).

**Comment by michalbcz** [comment]
Great. You were really fast!

**Comment by herby** [comment]
Website needed update anyway, it stalled back in days of 0.14.3.
