### ISSUE TITLE
.gitignore config.js and the.js

### ISSUE THREAD

**Issue by herby** [amber-smalltalk/trysmalltalk#5]
Do you see this project more as an app or as a library?
If the former, just ignore and close this.
If the latter, the [.gitignore](https://github.com/amber-smalltalk/trysmalltalk/blob/master/.gitignore) and bower.json ignore section should probably include /config.js and /the.js.

**Comment by hhzl** [comment]
Argument in favor of a library: people can add the project to their own project after ``amber init`` to construct their own amber home page.

**Comment by herby** [comment]
Yeah, I was think to include it there by default, on the devel side only (as the example to study and borrow from).

Hannes Hirzel wrote:

**Comment by tomrake** [comment]
I see this as a library, a reuseable piece of software. When I did the gh-page I use that library, the .webpage at http://amber-lang.org/learn.com uses the same library.

**Comment by herby** [comment]
Nothing, in fact ;-). Any app is a library in Amber, but some details are better suited for the lib, like actually being registered in bower, and having config.js and the.js in .gitignore as well as in bower.json ignore section (if you want to publish as little as possible, you can include devel.js, deploy.js and Gruntfile.js as well in bower ignore section).

Hannes Hirzel wrote:
> OK, so let's move ahead and declare it as a library. What needs to be
> done for this?
>
> On 1/8/15, Tom Rake <notifications@github.com> wrote:
> > I see this as a library, a reuseable piece of software. When I did the
> > gh-page I use that library, the .webpage at 
> http://amber-lang.org/learn.com
> > uses the same library.
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> > 
> https://github.com/amber-smalltalk/trysmalltalk/issues/5#issuecomment-69252850 
>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/amber-smalltalk/trysmalltalk/issues
/5#issuecomment-69309835>.
>

**Comment by sebastianconcept** [comment]
Well calling those _some details_ a nothing is forcing things.

Maybe is nothing additionally in Smalltalk but to get it done you need to do all that (and know why)

**Comment by herby** [comment]
In called it "some details" because they are 1/ just a few small things and 2/ it works without them, so they are not so critical.

In fact, every project is lib as well as app at the same time. It is upon you whether you tweak the details to better suite to library use case or to better suite to app use case.

Sebastian Sastre wrote:

**Comment by tomrake** [comment]
My analysis that the.js and config.js are actually built by the Gruntfile.js, can be built by the developer from the other files, they should not be under version control.

**Comment by herby** [comment]
For an application, it may make sense, to upload config.js and the.js after `grunt deploy` if deployment is done by pure git clone / git pull. For library, it makes no sense I can see.

Tom Rake wrote:

**Comment by hhzl** [comment]
A possible argument in favor of including config.js and the.js and
have the repo in a deploy state:

A user who wants to see what the app does may just download
https://github.com/amber-smalltalk/trysmalltalk/archive/master.zip
unpack and open index.html

Otherwise all the steps described here
https://github.com/amber-smalltalk/trysmalltalk#tools-needed

have to be done if there is no Amber environment yet.

**Comment by tomrake** [comment]
I just tried to serve the repo before `npm install` `bower install` `grunt devel` on Chrome I get a blank page and the debugger reports failed to load the.js  this gives the a new user no clue. 

IMHO, The README should say install the requirments (Node, grunt, amber cli). Then build the module by npm install, bower install grunt devel. The README should point to the website with detailed instructions.

**Comment by herby** [comment]
Tom Rake wrote:
> IMHO, The README should say install the requirments (Node, grunt, 
> amber cli).

... and git. Bower needs it to work. And you probably meant grunt-cli, not grunt.
You change the README default project has, in grunt-init-amber repo, if you think every project created by `amber init` should have this list as well.

**Comment by sebastianconcept** [comment]
+1 in making this a library.

@tomrake I agree on generally not versioning files that are generated by code (be either config stuff or builds). But it seems to make sense to add the builds when you want it published in bower facilitating its use by third parties.

Your final app can and should evade versioning `the.js` and `config.js` and even `src/*.js` so you can use your favourite CI and orchestration technique to get it deployed

**Comment by hhzl** [comment]
@tomrake I have updated the [README](https://github.com/amber-smalltalk/trysmalltalk/blob/master/README.md) to include the prerequisites. I copied it from [amber-examples](https://github.com/amber-smalltalk/amber-examples).

**Comment by hhzl** [comment]
@herby Yes, I think that every ``amber init`` generated project should include either

- a list of prerequisits
- a link to such a list

**Comment by tomrake** [comment]
I would change "Git for Windows" to "msysGit" the link download the correct file. I don't want to confuse the user. msysGit is required by bower.

**Comment by herby** [comment]
But you do not need msysGit. You need Git for Windiws, msysGir is something different. "Git for Windows" is the correct name of the product that users are to download and use. "msysGit" is the package for those that develop Git for Windows.

**Comment by herby** [comment]
(that said, link should go to msysgit.github.io, not msysgit.github.com, afaict)

**Comment by hhzl** [comment]
Link changed to msysgit.github.io

**Comment by herby** [comment]
Isn't this already solved and should be closed?
