### ISSUE TITLE
Add a table of contents (TOC)?

### ISSUE THREAD

**Issue by hhzl** [amber-smalltalk/trysmalltalk#6]
There are 24 slides at the moment (to check).

It might be good to have a small table of contents with about three or four entries to jump to a particular slide.

Are there some topics which are missing?

**Comment by hhzl** [comment]
The class comment of ``ProfStef``  claims that

      ProfStef contents


gives a table of contents.

**Comment by sebastianconcept** [comment]
@hhzl yes, good point. 

The page is being completely redesign and a TOC is one of the things that will include

**Comment by tomrake** [comment]
The way the page works now on http://amber-lang.org//learn.html the use has to know the Smalltalk language to navigate from page to page, this is a good thing. I think the focus to teach a newbie Smalltalk which I think is the purpose of the ProfStef example in the first place.

Yes we can extend the example with a TOC and possible nav features but is that good for the newbie focus?

**Comment by sebastianconcept** [comment]
I think not setting expectations is a bad idea, the TOC sets the right ones.

The focus is managed with design, the TOC is far from becoming the primary thing.

Is going to be like the railway of a staircase.
