### ISSUE TITLE
Update to 0.14.1 compliant structure

### ISSUE THREAD

**Issue by herby** [amber-smalltalk/trysmalltalk#7]
0.14.0 to 0.14.1 change needs slight change (except bumping dependency of amber itself) in project, as shown in https://github.com/amber-smalltalk/amber/wiki/Migration-from-0.14.0-to-0.14.1.

**Comment by hhzl** [comment]
@herby 

Is this OK?

https://github.com/amber-smalltalk/trysmalltalk/pull/12
