### ISSUE TITLE
Test if all slides work fine

### ISSUE THREAD

**Issue by hhzl** [amber-smalltalk/trysmalltalk#9]
Retest if all 24 pages are fine.

**Comment by herby** [comment]
Ctrl+D does not work as DoIt on Chrome / Win (probably update CodeMirror).

**Comment by hhzl** [comment]
Ctrl+d on FF / Linux Mint deletes the selected code snippet instead of executing it.

**Comment by hhzl** [comment]
All slides tested. OK. Besides the Ctrl+D issue it is fine.
